/**
 * ReeveOS Design Engine — The Brain
 *
 * Express server on port 4100 that lives on the GhostPost VPS.
 * Receives requests from Rezvo's AI Builder and returns
 * DESIGN.MD files generated by Ollama using:
 *   - Scientific dimension data (Reinecke & Gajos 2014)
 *   - Industry-specific recipes (18 industries)
 *   - Design intelligence from analysed websites (312+ reports)
 *
 * This is the piece that makes our AI Builder smarter than
 * competitors — design decisions based on DATA, not guessing.
 */

const express = require('express');
const cors = require('cors');
const fs = require('fs');
const path = require('path');

const app = express();
app.use(cors());
app.use(express.json());

const PORT = 4100;
const OLLAMA_URL = 'http://localhost:11434/api/generate';
const API_KEY = 'lmGwbvllpIqIrKROOCLgE5Z941MKP5EYfbkgwtqJZGigfXUTpuYRpNQkCqShmm6r';

// ═══════════════════════════════════════════════════════════
// LOAD DATA FILES ON STARTUP
// ═══════════════════════════════════════════════════════════

const dataDir = path.join(__dirname, '..', 'data');

let ollamaSystemPrompt = '';
let industryRecipes = {};
let designSpace = {};

try {
  ollamaSystemPrompt = fs.readFileSync(path.join(dataDir, 'ollama-system-prompt.md'), 'utf-8');
  console.log(`[Design Engine] Loaded Ollama system prompt (${ollamaSystemPrompt.length} chars)`);
} catch (e) {
  console.error('[Design Engine] FAILED to load ollama-system-prompt.md:', e.message);
}

try {
  industryRecipes = JSON.parse(fs.readFileSync(path.join(dataDir, 'industry-recipes.json'), 'utf-8'));
  const count = Object.keys(industryRecipes).filter(k => k !== '_note').length;
  console.log(`[Design Engine] Loaded ${count} industry recipes`);
} catch (e) {
  console.error('[Design Engine] FAILED to load industry-recipes.json:', e.message);
}

// Design space can be copied from Rezvo or generated locally
const dsPath = path.join(dataDir, 'design-space.json');
if (fs.existsSync(dsPath)) {
  try {
    designSpace = JSON.parse(fs.readFileSync(dsPath, 'utf-8'));
    console.log('[Design Engine] Loaded design space intelligence');
  } catch (e) {
    console.warn('[Design Engine] design-space.json exists but failed to parse:', e.message);
  }
} else {
  console.warn('[Design Engine] No design-space.json found — will work without intelligence data');
}


// ═══════════════════════════════════════════════════════════
// API KEY AUTH
// ═══════════════════════════════════════════════════════════

function authMiddleware(req, res, next) {
  const key = req.headers['x-api-key'] || req.query.key;
  if (key !== API_KEY) {
    return res.status(401).json({ error: 'Invalid API key' });
  }
  next();
}


// ═══════════════════════════════════════════════════════════
// HEALTH CHECK
// ═══════════════════════════════════════════════════════════

app.get('/api/health', (req, res) => {
  res.json({
    status: 'ok',
    service: 'design-engine',
    port: PORT,
    data: {
      systemPrompt: ollamaSystemPrompt.length > 0,
      recipes: Object.keys(industryRecipes).filter(k => k !== '_note').length,
      intelligence: Object.keys(designSpace?.industries || {}).length,
    },
    timestamp: new Date().toISOString(),
  });
});


// ═══════════════════════════════════════════════════════════
// INDUSTRY DETECTION
// ═══════════════════════════════════════════════════════════

function detectIndustry(prompt) {
  const lower = (prompt || '').toLowerCase();
  const mappings = {
    barber: ['barber', 'barbershop', 'haircut', 'fade', 'shave', 'grooming', "men's hair"],
    hair_salon: ['salon', 'hair salon', 'hairdresser', 'styling'],
    beauty_salon: ['beauty salon', 'beauty', 'lashes', 'brows', 'makeup artist'],
    nail_salon: ['nail', 'manicure', 'pedicure', 'gel nails'],
    aesthetics_clinic: ['aesthetics', 'skin clinic', 'botox', 'filler', 'microneedling', 'rejuvenate', 'cosmetic'],
    restaurant: ['restaurant', 'dining', 'bistro', 'brasserie', 'eatery', 'fine dining', 'grill'],
    cafe: ['cafe', 'coffee', 'coffee shop', 'bakery', 'tea room', 'patisserie'],
    gym: ['gym', 'fitness', 'crossfit', 'boxing', 'martial arts', 'weight', 'training'],
    personal_trainer: ['personal trainer', 'pt', 'fitness coach'],
    yoga_pilates: ['yoga', 'pilates', 'meditation', 'mindfulness', 'wellness studio'],
    spa_wellness: ['spa', 'wellness', 'massage', 'day spa', 'retreat'],
    tattoo_piercing: ['tattoo', 'piercing', 'ink', 'tattoo studio', 'body art'],
    dental: ['dental', 'dentist', 'orthodont', 'teeth', 'smile'],
    physiotherapy: ['physio', 'physiotherapy', 'chiropract', 'osteopath'],
    photography: ['photography', 'photographer', 'photo studio', 'portrait'],
    veterinary: ['vet', 'veterinary', 'animal', 'pet'],
    tutoring: ['tutor', 'tutoring', 'teaching', 'education', 'lessons'],
  };

  for (const [industry, keywords] of Object.entries(mappings)) {
    for (const kw of keywords) {
      if (lower.includes(kw)) return industry;
    }
  }
  return 'generic_business';
}


// ═══════════════════════════════════════════════════════════
// BUILD THE FULL OLLAMA PROMPT
// ═══════════════════════════════════════════════════════════

function buildOllamaPrompt(industry, prompt, businessName, businessInfo) {
  const recipe = industryRecipes[industry] || industryRecipes['generic_business'] || {};
  const intelligence = designSpace?.industries?.[industry] || null;

  let userPrompt = '';

  // Business context
  userPrompt += `BUSINESS: ${businessName || 'Unnamed Business'}\n`;
  userPrompt += `INDUSTRY: ${industry.replace(/_/g, ' ')}\n`;
  if (businessInfo) {
    userPrompt += `INFO: ${businessInfo}\n`;
  }
  userPrompt += `USER REQUEST: ${prompt}\n\n`;

  // Industry recipe
  if (recipe.sections) {
    userPrompt += `INDUSTRY RECIPE:\n`;
    userPrompt += `  Sections: ${recipe.sections.join(' → ')}\n`;
    userPrompt += `  Hero content: ${recipe.hero_content || 'Standard hero'}\n`;
    userPrompt += `  Key features: ${(recipe.key_features || []).join(', ')}\n`;
    userPrompt += `  Tone: ${recipe.tone || 'professional'}\n`;
    userPrompt += `  Imagery: ${recipe.imagery_notes || 'Industry-appropriate photography'}\n\n`;
  }

  // Design intelligence (the science)
  if (intelligence && intelligence.dimensions) {
    const d = intelligence.dimensions;
    userPrompt += `DESIGN INTELLIGENCE (from ${intelligence.count || 0} analysed real websites):\n`;
    userPrompt += `  Target coordinates for this industry:\n`;
    userPrompt += `  visual_complexity=${d.visual_complexity || 5} `;
    userPrompt += `colourfulness=${d.colourfulness || 5} `;
    userPrompt += `prototypicality=${d.prototypicality || 5} `;
    userPrompt += `warmth=${d.warmth || 5}\n`;
    userPrompt += `  typography_weight=${d.typography_weight || 5} `;
    userPrompt += `image_dominance=${d.image_dominance || 5} `;
    userPrompt += `contrast_level=${d.contrast_level || 5} `;
    userPrompt += `layout_density=${d.layout_density || 5}\n\n`;
    userPrompt += `  These are the AVERAGE dimension scores from real successful websites in this industry.\n`;
    userPrompt += `  Your design brief should cluster near these targets.\n\n`;
  }

  // Override: we want a SINGLE design system, not 3 variations
  // (Rezvo Phase 1 expects one DESIGN.MD, not three)
  userPrompt += `IMPORTANT: Generate a SINGLE design system document (not 3 variations).\n`;
  userPrompt += `Output it in this format:\n\n`;
  userPrompt += `# Design System: [Creative Name]\n\n`;
  userPrompt += `## 1. Creative North Star\n`;
  userPrompt += `[2-3 sentences — the vision, the metaphor, the feeling]\n\n`;
  userPrompt += `## 2. Colours\n`;
  userPrompt += `CSS custom properties in :root {}. 7 tokens: --bg-page, --bg-surface, --bg-surface-raised, --text-primary, --text-muted, --accent-primary, --accent-secondary\n`;
  userPrompt += `Surface Hierarchy Rule, Border Rule, Glass Rule\n\n`;
  userPrompt += `## 3. Typography\n`;
  userPrompt += `Google Fonts only. Heading font + weight, Body font + weight, Hero clamp() size, Hierarchy principle\n\n`;
  userPrompt += `## 4. Elevation & Depth\n`;
  userPrompt += `Shadow specs, hover effects, entrance animations\n\n`;
  userPrompt += `## 5. Layout\n`;
  userPrompt += `Hero approach, Nav style, Section flow (${(recipe.sections || []).join(' → ')}), Signature Element, Grid\n\n`;
  userPrompt += `## 6. Components\n`;
  userPrompt += `Buttons, Cards, Inputs, Images\n\n`;
  userPrompt += `## 7. Do's and Don'ts\n`;
  userPrompt += `3-4 specific positive rules. 3-4 specific bans.\n\n`;
  userPrompt += `HARD RULES: Never use Inter/Roboto. Never use purple-blue gradients. Never use a generic template layout. Use Unsplash search terms for images.\n`;

  return userPrompt;
}


// ═══════════════════════════════════════════════════════════
// CALL OLLAMA
// ═══════════════════════════════════════════════════════════

async function callOllama(systemPrompt, userPrompt) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 120000); // 2 min timeout

  try {
    const response = await fetch(OLLAMA_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: 'mistral',
        prompt: userPrompt,
        system: systemPrompt,
        stream: false,
        options: {
          temperature: 0.8,
          top_p: 0.9,
          num_predict: 2000,
        },
      }),
      signal: controller.signal,
    });

    clearTimeout(timeout);

    if (!response.ok) {
      const body = await response.text();
      throw new Error(`Ollama returned ${response.status}: ${body}`);
    }

    const data = await response.json();
    return data.response || '';
  } catch (err) {
    clearTimeout(timeout);
    throw err;
  }
}


// ═══════════════════════════════════════════════════════════
// MAIN ENDPOINT: POST /api/design-brief
// ═══════════════════════════════════════════════════════════

app.post('/api/design-brief', authMiddleware, async (req, res) => {
  const { industry: requestedIndustry, prompt, mood, business_name, business_info } = req.body;

  if (!prompt) {
    return res.status(400).json({ error: 'prompt is required' });
  }

  // Detect industry from prompt if not explicitly provided
  const industry = requestedIndustry || detectIndustry(prompt);

  console.log(`[Design Engine] Generating design brief — industry: ${industry}, prompt: "${prompt.substring(0, 80)}..."`);

  try {
    const userPrompt = buildOllamaPrompt(industry, prompt, business_name, business_info);
    const designSystem = await callOllama(ollamaSystemPrompt, userPrompt);

    if (!designSystem || designSystem.length < 100) {
      console.warn('[Design Engine] Ollama returned short/empty response');
      return res.status(502).json({ error: 'Ollama returned an insufficient response' });
    }

    console.log(`[Design Engine] Generated design system (${designSystem.length} chars) for ${industry}`);

    return res.json({
      status: 'ok',
      industry,
      design_system: designSystem,
      intelligence: designSpace?.industries?.[industry] || null,
      recipe: industryRecipes[industry] || null,
    });

  } catch (err) {
    console.error('[Design Engine] Error:', err.message);

    if (err.name === 'AbortError') {
      return res.status(504).json({ error: 'Ollama timed out (120s limit)' });
    }

    // Check if Ollama is even running
    if (err.message.includes('ECONNREFUSED') || err.message.includes('fetch failed')) {
      return res.status(503).json({ error: 'Ollama is not running. Start with: ollama serve' });
    }

    return res.status(500).json({ error: err.message });
  }
});


// ═══════════════════════════════════════════════════════════
// START
// ═══════════════════════════════════════════════════════════

app.listen(PORT, '0.0.0.0', () => {
  console.log(`[Design Engine] Running on port ${PORT}`);
  console.log(`[Design Engine] Health: http://localhost:${PORT}/api/health`);
  console.log(`[Design Engine] Brief:  POST http://localhost:${PORT}/api/design-brief`);
});
